<?php
// Register Custom Post Type
function init_post_types() {

	$labels = array(
		'name'                  => 'Wiadomości',
		'singular_name'         => 'Wiadomości',
		'menu_name'             => 'Wiadomości',
		'name_admin_bar'        => 'Wiadomości',
		'archives'              => 'Archiwa',
		'attributes'            => 'Atrybuty',
		'parent_item_colon'     => 'Rodzic',
		'all_items'             => 'Wszystkie',
		'add_new_item'          => 'Dodaj nowy',
		'add_new'               => 'Dodaj nowy',
		'new_item'              => 'Nowy',
		'edit_item'             => 'Edytuj',
		'update_item'           => 'Zaktualizuj',
		'view_item'             => 'Zobacz',
		'view_items'            => 'Zobacz',
		'search_items'          => 'Szukaj',
		'not_found'             => 'Nie znaleziono',
		'not_found_in_trash'    => 'Nie znalezionow w koszu',
		'featured_image'        => 'Zdjęcie wyrózniające',
		'set_featured_image'    => 'Ustaw zdjęcie',
		'remove_featured_image' => 'Usuń zdjęcie',
		'use_featured_image'    => 'Uzyj jako zdjęcie',
		'insert_into_item'      => 'Osadź',
		'uploaded_to_this_item' => 'Załaduj',
		'items_list'            => 'Lista',
		'items_list_navigation' => 'Navigacja',
		'filter_items_list'     => 'Filtruj',
	);
	$args = array(
		'label'                 => 'Wiadomości',
		'description'           => 'Wiadomości',
		'labels'                => $labels,
		'supports'              => array( 'title', 'editor', 'thumbnail', 'comments', 'custom-fields', 'page-attributes', 'post-formats' ),
		'taxonomies'            => array( 'wiadomosci_category', 'post_tag' ),
		'hierarchical'          => false,
		'public'                => true,
		'show_ui'               => true,
		'show_in_menu'          => true,
		'menu_position'         => 2,
		'show_in_admin_bar'     => true,
		'show_in_nav_menus'     => true,
		'can_export'            => true,
		'has_archive'           => false,
		'exclude_from_search'   => false,
		'publicly_queryable'    => true,
		'capability_type'       => 'post',
		'show_in_rest'          => false,
	);
    register_post_type( 'wiadomosci', $args );
    register_taxonomy(
        'wiadomosci_category',
        'wiadomosci',
        array(
            'label' => "Kategorie",
            'rewrite' => array( 'slug' => 'wiadomosci' ),
            'hierarchical' => true,
        )
    );

    /******************************************************************************/
    $labels = array(
		'name'                  => 'Kultura',
		'singular_name'         => 'Kultura',
		'menu_name'             => 'Kultura',
		'name_admin_bar'        => 'Kultura',
		'archives'              => 'Archiwa',
		'attributes'            => 'Atrybuty',
		'parent_item_colon'     => 'Rodzic',
		'all_items'             => 'Wszystkie',
		'add_new_item'          => 'Dodaj nowy',
		'add_new'               => 'Dodaj nowy',
		'new_item'              => 'Nowy',
		'edit_item'             => 'Edytuj',
		'update_item'           => 'Zaktualizuj',
		'view_item'             => 'Zobacz',
		'view_items'            => 'Zobacz',
		'search_items'          => 'Szukaj',
		'not_found'             => 'Nie znaleziono',
		'not_found_in_trash'    => 'Nie znalezionow w koszu',
		'featured_image'        => 'Zdjęcie wyrózniające',
		'set_featured_image'    => 'Ustaw zdjęcie',
		'remove_featured_image' => 'Usuń zdjęcie',
		'use_featured_image'    => 'Uzyj jako zdjęcie',
		'insert_into_item'      => 'Osadź',
		'uploaded_to_this_item' => 'Załaduj',
		'items_list'            => 'Lista',
		'items_list_navigation' => 'Navigacja',
		'filter_items_list'     => 'Filtruj',
	);
	$args = array(
		'label'                 => 'Kultura',
		'description'           => 'Kultura',
		'labels'                => $labels,
		'supports'              => array( 'title', 'editor', 'thumbnail', 'comments', 'custom-fields', 'page-attributes', 'post-formats' ),
		'taxonomies'            => array( 'kultura_category', 'post_tag' ),
		'hierarchical'          => false,
		'public'                => true,
		'show_ui'               => true,
		'show_in_menu'          => true,
		'menu_position'         => 2,
		'show_in_admin_bar'     => true,
		'show_in_nav_menus'     => true,
		'can_export'            => true,
		'has_archive'           => false,
		'exclude_from_search'   => false,
		'publicly_queryable'    => true,
		'capability_type'       => 'post',
		'show_in_rest'          => false,
	);
    register_post_type( 'kultura', $args );
    register_taxonomy(
        'kultura_category',
        'kultura',
        array(
            'label' => "Kategorie",
            'rewrite' => array( 'slug' => 'kultura' ),
            'hierarchical' => true,
        )
    );

        /******************************************************************************/
        $labels = array(
            'name'                  => 'Sport',
            'singular_name'         => 'Sport',
            'menu_name'             => 'Sport',
            'name_admin_bar'        => 'Sport',
            'archives'              => 'Archiwa',
            'attributes'            => 'Atrybuty',
            'parent_item_colon'     => 'Rodzic',
            'all_items'             => 'Wszystkie',
            'add_new_item'          => 'Dodaj nowy',
            'add_new'               => 'Dodaj nowy',
            'new_item'              => 'Nowy',
            'edit_item'             => 'Edytuj',
            'update_item'           => 'Zaktualizuj',
            'view_item'             => 'Zobacz',
            'view_items'            => 'Zobacz',
            'search_items'          => 'Szukaj',
            'not_found'             => 'Nie znaleziono',
            'not_found_in_trash'    => 'Nie znalezionow w koszu',
            'featured_image'        => 'Zdjęcie wyrózniające',
            'set_featured_image'    => 'Ustaw zdjęcie',
            'remove_featured_image' => 'Usuń zdjęcie',
            'use_featured_image'    => 'Uzyj jako zdjęcie',
            'insert_into_item'      => 'Osadź',
            'uploaded_to_this_item' => 'Załaduj',
            'items_list'            => 'Lista',
            'items_list_navigation' => 'Navigacja',
            'filter_items_list'     => 'Filtruj',
        );
        $args = array(
            'label'                 => 'Sport',
            'description'           => 'Sport',
            'labels'                => $labels,
            'supports'              => array( 'title', 'editor', 'thumbnail', 'comments', 'custom-fields', 'page-attributes', 'post-formats' ),
            'taxonomies'            => array( 'sport_category', 'post_tag' ),
            'hierarchical'          => false,
            'public'                => true,
            'show_ui'               => true,
            'show_in_menu'          => true,
            'menu_position'         => 2,
            'show_in_admin_bar'     => true,
            'show_in_nav_menus'     => true,
            'can_export'            => true,
            'has_archive'           => false,
            'exclude_from_search'   => false,
            'publicly_queryable'    => true,
            'capability_type'       => 'post',
            'show_in_rest'          => false,
        );
        register_post_type( 'sport', $args );
        register_taxonomy(
            'sport_category',
            'sport',
            array(
                'label' => "Kategorie",
                'rewrite' => array( 'slug' => 'sport' ),
                'hierarchical' => true,
            )
        );
		
		/******************************************************************************/
		$labels = array(
			'name'                  => 'Nasze myki',
			'singular_name'         => 'Nasze myki',
			'menu_name'             => 'Nasze myki',
			'name_admin_bar'        => 'Nasze myki',
			'archives'              => 'Archiwa',
			'attributes'            => 'Atrybuty',
			'parent_item_colon'     => 'Rodzic',
			'all_items'             => 'Wszystkie',
			'add_new_item'          => 'Dodaj nowy',
			'add_new'               => 'Dodaj nowy',
			'new_item'              => 'Nowy',
			'edit_item'             => 'Edytuj',
			'update_item'           => 'Zaktualizuj',
			'view_item'             => 'Zobacz',
			'view_items'            => 'Zobacz',
			'search_items'          => 'Szukaj',
			'not_found'             => 'Nie znaleziono',
			'not_found_in_trash'    => 'Nie znalezionow w koszu',
			'featured_image'        => 'Zdjęcie wyrózniające',
			'set_featured_image'    => 'Ustaw zdjęcie',
			'remove_featured_image' => 'Usuń zdjęcie',
			'use_featured_image'    => 'Uzyj jako zdjęcie',
			'insert_into_item'      => 'Osadź',
			'uploaded_to_this_item' => 'Załaduj',
			'items_list'            => 'Lista',
			'items_list_navigation' => 'Navigacja',
			'filter_items_list'     => 'Filtruj',
		);
		$args = array(
			'label'                 => 'Nasze myki',
			'description'           => 'Nasze myki',
			'labels'                => $labels,
			'supports'              => array( 'title', 'editor', 'thumbnail', 'comments', 'custom-fields', 'page-attributes', 'post-formats' ),
			'taxonomies'            => array( 'nasze_myki_category', 'post_tag' ),
			'hierarchical'          => false,
			'public'                => true,
			'show_ui'               => true,
			'show_in_menu'          => true,
			'menu_position'         => 2,
			'show_in_admin_bar'     => true,
			'show_in_nav_menus'     => true,
			'can_export'            => true,
			'has_archive'           => false,
			'exclude_from_search'   => false,
			'publicly_queryable'    => true,
			'capability_type'       => 'post',
			'show_in_rest'          => false,
		);
		register_post_type( 'nasze_myki', $args );
		register_taxonomy(
			'nasze_myki_category',
			'nasze_myki',
			array(
				'label' => "Kategorie",
				'rewrite' => array( 'slug' => 'nasze-myki' ),
				'hierarchical' => true,
				)
			);

		/******************************************************************************/
		$labels = array(
			'name'                  => 'Nasz fyrtel',
			'singular_name'         => 'Nasz fyrtel',
			'menu_name'             => 'Nasz fyrtel',
			'name_admin_bar'        => 'Nasz fyrtel',
			'archives'              => 'Archiwa',
			'attributes'            => 'Atrybuty',
			'parent_item_colon'     => 'Rodzic',
			'all_items'             => 'Wszystkie',
			'add_new_item'          => 'Dodaj nowy',
			'add_new'               => 'Dodaj nowy',
			'new_item'              => 'Nowy',
			'edit_item'             => 'Edytuj',
			'update_item'           => 'Zaktualizuj',
			'view_item'             => 'Zobacz',
			'view_items'            => 'Zobacz',
			'search_items'          => 'Szukaj',
			'not_found'             => 'Nie znaleziono',
			'not_found_in_trash'    => 'Nie znalezionow w koszu',
			'featured_image'        => 'Zdjęcie wyrózniające',
			'set_featured_image'    => 'Ustaw zdjęcie',
			'remove_featured_image' => 'Usuń zdjęcie',
			'use_featured_image'    => 'Uzyj jako zdjęcie',
			'insert_into_item'      => 'Osadź',
			'uploaded_to_this_item' => 'Załaduj',
			'items_list'            => 'Lista',
			'items_list_navigation' => 'Navigacja',
			'filter_items_list'     => 'Filtruj',
		);
		$args = array(
			'label'                 => 'Nasz fyrtel',
			'description'           => 'Nasz fyrtel',
			'labels'                => $labels,
			'supports'              => array( 'title', 'editor', 'thumbnail', 'comments', 'custom-fields', 'page-attributes', 'post-formats' ),
			'taxonomies'            => array( 'nasz_fyrtel_category', 'post_tag' ),
			'hierarchical'          => false,
			'public'                => true,
			'show_ui'               => true,
			'show_in_menu'          => true,
			'menu_position'         => 2,
			'show_in_admin_bar'     => true,
			'show_in_nav_menus'     => true,
			'can_export'            => true,
			'has_archive'           => false,
			'exclude_from_search'   => false,
			'publicly_queryable'    => true,
			'capability_type'       => 'post',
			'show_in_rest'          => false,
		);
		register_post_type( 'nasz_fyrtel', $args );
		register_taxonomy(
			'nasz_fyrtel_category',
			'nasz_fyrtel',
			array(
				'label' => "Kategorie",
				'rewrite' => array( 'slug' => 'nasz-fyrtel' ),
				'hierarchical' => true,
				)
			);

	}
add_action( 'init', 'init_post_types', 0 );